"""Render a human-reviewable, GitHub-style PR summary.

This is the artifact a human approves. It makes the five judging questions
answerable from the product itself: what changed, where, what patch, how we
know it works, and the explicit human-review gate.
"""

import os

from patchahead import paths
from patchahead.schemas import BreakingChange, ImpactReport, PatchResult, TestRun

TITLE = "Update Orders API integration for cursor-based pagination"


def _rel(p):
    try:
        return os.path.relpath(p, paths.ROOT)
    except Exception:
        return p


def render(
    bc: BreakingChange,
    impact: ImpactReport,
    patch: PatchResult,
    before: TestRun,
    after: TestRun,
) -> str:
    files = "\n".join(f"- `{_rel(f)}`" for f in patch.files_changed)
    patterns = "\n".join(f"- `{p}`" for p in impact.old_patterns_found) or "- _none_"
    engine = "Claude" if patch.source == "llm" else "deterministic transform"

    return f"""# {TITLE}

> Generated by **PatchAhead** — proposed, not merged. Review before approving.

## Summary
Upstream **{bc.title}** shipped a breaking change. PatchAhead detected it,
located the affected downstream code, and migrated it. The same integration
test that was failing now passes.

## 1. Upstream breaking change
- **Type:** `{bc.change_type}` &nbsp;•&nbsp; **Risk:** `{bc.risk_level}`
- **Before:** {bc.old_behavior}
- **After:** {bc.new_behavior}
- **Migration:** {bc.migration_hint}

## 2. Downstream impact
- **Confidence:** {impact.confidence}
- **Affected functions:** {", ".join(f"`{fn}`" for fn in impact.affected_functions) or "_none_"}
- **Old-contract usage found:**
{patterns}

## 3. Patch applied
- **Files changed:**
{files}
- **Engine:** {engine}{" (fallback)" if patch.fallback_used and patch.source != "llm" else ""}
- **Explanation:** {patch.patch_explanation}

```diff
{patch.diff.rstrip()}
```

## 4. Test evidence
| Stage | Command | Result |
|-------|---------|--------|
| Before | `pytest demo/downstream/tests (ORDERS_API_VERSION=v2)` | ❌ {before.summary} |
| After  | `pytest demo/downstream/tests (ORDERS_API_VERSION=v2)` | ✅ {after.summary} |

## 5. Risk & human review
- **Risk level:** `{patch.risk_level}`
- **Auto-merge:** ❌ disabled — this PR requires human approval.

### Review checklist
- [ ] Upstream change is correctly characterized
- [ ] Patch is minimal and preserves the public signature
- [ ] Tests meaningfully cover the migrated behavior
- [ ] No unrelated changes introduced
"""
